[package]
name = "impl_serde_serialize_error"
version = "1.0.0"
edition = "2021"
description = "Macro for fast implementing error methods in serde::Serializer trait"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"

[dev-dependencies]
thiserror = "1.0"